<?php
return [
    [
        'model' => 'webniu',
        'plugin' => 'webniu',
        'path' => 'admin',
        'key' => 'admin',
        'title' => '后台管理',
        'type' => 0,
        'icon' => 'ri:list-view',
        'component' => '/admin/index/index',
        'children' => [
            [
                'path' => 'console',
                'key' => 'console',
                'title' => '控制台',
                'type' => 0,
                'icon' => 'ri:pie-chart-line',
                'component' => '',
                'children' => [
                    [
                        'path' => 'dashboard',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\DashboardController',
                        'title' => '数据面板',
                        'type' => 1,
                        'fixed_tab' => 1,
                        'icon' => 'ri:line-chart-line',
                        'component' => '/admin/dashboard',
                    ],
                ],
            ],
            [
                'path' => 'basicsite',
                'key' => 'basicsite',
                'title' => '核心设置',
                'type' => 0,
                'icon' => 'ri:settings-2-line',
                'component' => '',
                'children' => [
                    [
                        'path' => 'config',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\ConfigController',
                        'title' => '系统设置',
                        'type' => 1,
                        'icon' => 'ri:settings-2-line',
                        'component' => '/admin/config',
                        'children' => [],
                    ],
                    [
                        'path' => 'rule',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\RuleController',
                        'title' => '菜单管理',
                        'type' => 1,
                        'icon' => 'ri:menu-fill',
                        'component' => '/admin/rule',
                        'children' => [],
                    ],
                ],
            ],
            [
                'path' => 'general',
                'key' => 'general',
                'title' => '通用设置',
                'type' => 0,
                'icon' => 'ri:side-bar-line',
                'component' => '',
                'children' => [
                    [
                        'path' => 'upload',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\UploadController',
                        'title' => '附件管理',
                        'type' => 1,
                        'icon' => 'ri:share-2-line',
                        'component' => '/admin/upload',
                        'children' => [],
                    ],
                    [
                        'path' => 'confset',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\ConfsetController',
                        'title' => '配置管理',
                        'type' => 1,
                        'icon' => 'ri:booklet-line',
                        'component' => '/admin/confset',
                        'children' => [],
                    ],
                    [
                        'path' => 'article',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\ArticleController',
                        'title' => '系统公告',
                        'type' => 1,
                        'icon' => 'ri:chat-ai-2-line',
                        'component' => '/admin/system/general',
                        'children' => [],
                    ],
                    [
                        'path' => 'emailtemp',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\EmailTempController',
                        'title' => '邮件模板',
                        'type' => 1,
                        'icon' => 'ri:message-ai-3-line',
                        'component' => '/admin/emailtemp',
                        'children' => [],
                    ],
                    [
                        'path' => 'smstemp',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\SmsTempController',
                        'title' => '短信模板',
                        'type' => 1,
                        'icon' => 'ri:message-2-line',
                        'component' => '/admin/smstemp',
                        'children' => [],
                    ],
                    [
                        'path' => 'dict',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\DictController',
                        'title' => '字典管理',
                        'type' => 1,
                        'icon' => 'ri:book-marked-line',
                        'component' => '/admin/dict',
                        'children' => [],
                    ],
                    [
                        'path' => 'quick',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\QuickController',
                        'title' => '快捷入口',
                        'type' => 1,
                        'icon' => 'ri:book-marked-line',
                        'component' => '/admin/quick',
                        'children' => [],
                    ],
                ],
            ],
            [
                'path' => 'accpower',
                'key' => 'accpower',
                'title' => '账户管理',
                'type' => 0,
                'icon' => 'ri:group-line',
                'component' => '',
                'children' => [
                    [
                        'path' => 'role',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\RoleController',
                        'title' => '权限管理',
                        'type' => 1,
                        'icon' => 'ri:admin-line',
                        'component' => '/admin/role',
                        'children' => [],
                    ],
                    [
                        'path' => 'admins',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\AdminController',
                        'title' => '账户列表',
                        'type' => 1,
                        'icon' => 'ri:user-star-line',
                        'component' => '/admin/admins',
                        'children' => [],
                    ],
                    [
                        'path' => 'userinfo',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\AccountController',
                        'title' => '基本资料',
                        'type' => 1,
                        'is_hide' => 1,
                        'icon' => 'ri:contacts-line',
                        'active_path' => '/admin/accpower/admins',
                        'component' => '/admin/user/account',
                        'children' => [],
                    ],
                    [
                        'path' => 'logtime',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\LogtimeController',
                        'title' => '登录日志',
                        'type' => 1,
                        'icon' => 'ri:bill-line',
                        'component' => '/admin/logtime',
                        'children' => [],
                    ],
                ],
            ],
            [
                'path' => 'users',
                'key' => 'users',
                'title' => '会员管理',
                'type' => 0,
                'icon' => 'ri:user-3-line',
                'component' => '',
                'children' => [
                    [
                        'path' => 'user',
                        'key' => 'plugin\\webniu\\app\\admin\\controller\\UserController',
                        'title' => '会员列表',
                        'type' => 1,
                        'icon' => 'ri:user-line',
                        'component' => '/admin/user',
                        'children' => [],
                    ],
                ],
            ],
        ],
    ],
    [
        'model' => 'webniu',
        'plugin' => 'webniu',
        'path' => 'apps',
        'key' => 'apps',
        'title' => '应用插件',
        'type' => 0,
        'icon' => 'ri:function-ai-line',
        'component' => '/admin/index/index',
        'children' => [
            [
                'path' => 'plugin',
                'key' => 'plugin\\webniu\\app\\admin\\controller\\PluginController',
                'title' => '应用列表',
                'type' => 1,
                'icon' => 'ri:list-check-2',
                'component' => '/apps/plugin',
                'children' => [],
            ],
            [
                'path' => 'storeurl',
                'name' => 'storeurl',
                'key' => 'storeurl',
                'title' => '应用市场',
                'link' => 'https://store.webniu.com/',
                'is_iframe' => 1,
                'keep_alive' => 1,
                'type' => 3,
                'icon' => 'ri:shopping-bag-3-line',
            ],
        ],
    ],
];
